version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  groups:
    opentelemetry:
      patterns:
        - "tracing*"
        - "opentelemetry*"
        - "tonic*"

    azure:
      patterns:
        - "azure*"
- package-ecosystem: github-actions
  directory: .github/workflows
  schedule:
    interval: daily
- package-ecosystem: terraform
  directory: "/infra"
  schedule:
    interval: daily
