version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: .github/workflows
  schedule:
    interval: daily
- package-ecosystem: terraform
  directory: "/infra"
  schedule:
    interval: daily
