workspace:
    base: /go
    path: src/github.com/SierraSoftworks/bender

pipeline:
    publish:docker:
        image: plugins/docker
        repo: sierrasoftworks/bender
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"
            - "SENTRY_DSN=$${SENTRY_DSN}"
        secrets: [ docker_username, docker_password, sentry_dsn ]

    sentry:release:
      image: sierrasoftworks/drone-sentry:latest
      organization: open-source
      project: bender

      release: true
      release_version: "${DRONE_COMMIT_SHA}"
      release_url: "${DRONE_COMMIT_LINK}"

      secrets:
        - sentry_server
        - sentry_token

    sentry:deploy:
      image: sierrasoftworks/drone-sentry:latest
      organization: open-source
      project: bender

      release_version: "${DRONE_COMMIT_SHA}"

      deploy: true
      deploy_environment: "Docker Hub"
      deploy_name: "sierrasoftworks/bender:${DRONE_COMMIT_BRANCH}"
      deploy_url: "https://hub.docker.com/r/sierrasoftworks/bender/"

      secrets:
        - sentry_server
        - sentry_token