trigger:
  - master
  
variables:
  tag: '$(Build.BuildId)'
  image: sierrasoftworks/bender

resources:
  repositories:
    - repository: templates
      type: github
      name: SierraSoftworks/devops-pipelines
      endpoint: SierraSoftworks
  
extends:
  template: kubernetes/app.yml@templates
  parameters:
    build:
      - job: build_docker
        displayName: Build Docker Image
        steps:
        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            command: buildAndPush
            dockerfile: 'Dockerfile'
            containerRegistry: Docker Hub
            repository: $(image)
            tags: |
              latest
              $(tag)
    manifests: ./.deploy
    containers: |
      $(image):$(tag)
    staging:
      namespace: bender-staging
      environment: staging-bender-sierrasoftworks-com.bender-staging
      healthcheck: https://staging.bender.sierrasoftworks.com/api/v1/quote
    production:
      namespace: bender-prod
      environment: bender-sierrasoftworks-com.bender-prod
      healthcheck: https://bender.sierrasoftworks.com/api/v1/quote
