name: Deploy Azure Function
on:
  push:
    branches: [ main, feature/azure-function ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  HANDLER_NAME: bender
  AZURE_FUNCTIONAPP_NAME: bender-sierrasoftworks

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  build:
    needs: test
    if: github.event_name == 'push'

    runs-on: ubuntu-20.04

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools

      - uses: actions/checkout@v2

      - name: Get Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: "x86_64-unknown-linux-musl"
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Build Handler
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-unknown-linux-musl

      - run: cp target/release/$HANDLER_NAME ./

      - name: Save handler artifact
        uses: actions/upload-artifact@v2
        with:
          name: handler
          path: handler

  deploy:
    needs: build
    if: github.event_name == 'push'

    runs-on: ubuntu-20.04

    steps:
      - name: Fetch handler artifact
        uses: actions/download-artifact@v2
        with:
          name: handler
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          respect-funcignore: 'true'
      